server:
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: create-drop # auto create schema
    show_sql: true
    generate-ddl: true
    properties:
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: admin

logging:
  level:
    org.springframework.web: error
    org.springframework.jdbc.datasoruce: error
    org.hibernate: error

# Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
# Because detection is disabled you have to set correct dialect by hand.
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect